"""empty message

Revision ID: db18598ece90
Revises: 3c85c65c9b1f
Create Date: 2023-03-27 10:51:49.244192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db18598ece90'
down_revision = '3c85c65c9b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=mysql.VARCHAR(length=80),
                              type_=sa.String(length=100),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.alter_column('name',
                              existing_type=sa.String(length=100),
                              type_=mysql.VARCHAR(length=80),
                              existing_nullable=False)

    # ### end Alembic commands ###
